travis:
  secure:
    BINSTAR_TOKEN: Ugx7MeWcnCSH+KdOC3aOOYbYK5eNuqhHGPy52B8iziMqmuS8ZOrYFtpJxHYTSFqWpscHnFNTcfsqfmvJ+NOa/XTd2nK9e+5ptPx7bGOz4mkL1Wr12SSEejVX+mow7lbDGTa24YzCb9sR5SB49T45oaIfimDkEXSwIswc4/j8NMGXBJVt+efg97dd7nUYqWG1RXO8ztnIogPatxiJKlrKVKPPplgOExTQMDZkEnB44jULhpb9j7TCcoxc36ZRvyyj1nzXXeqD578fbBlJ1uB3uX6ctGNbC/3nUnj6f2mNlslMuxajQbdzWm8eEZ10ajLxQhCGMmL9wo5mWsukL0PUfqVGepbfa00ox/eikv3OzGFLjZbgxoRDAlOEwaGaNPm5JnqP93l4X7owf6VTeAbXjHNOJ9VpVJF97aI8ZAnB+8hapIKOCTO2l6HBdvKwvAVCNmmT2Aqk6dl8KGnDm9QA2Y1jK1+49wYXZXOfZCDYApJDzd/dfjq1isfMpm3OPtTC3BzrrWpkFxx8XN/CN2lg4UFb19ZpqHiGXe+K539Bsx6AwusRwozn12u0nmmN/f/b8JTK3AIW7WGd5GrFRaikNviUEOql/iLabGUBXB8U5t7UBigJgIX8K5JuZyTzeLj389LSqB3ts978goGLfb82ejEflTsnYChzCIpnmBmNMPE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
